# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CODE4WD Conf
email: fogell@code4wd.com
description: > # this means to ignore newlines until "baseurl:"
  The largest OSS event on the Middle East
baseurl: "/code4wd-experiments" # the subpath of your site, e.g. /blog
url: "http://code4wd.com" # the base hostname & protocol for your site
twitter_username: fogelmania
github_username:  fogelmania

asset_path: "/bucket"

collections:
- talks
- speakers
- patterns

# this is just to ovverride the default content of exclude
# see https://jekyllrb.com/docs/configuration/
exclude:
- none

# this does not work
# if the order on https://jekyllrb.com/docs/configuration/ is relevant,
# exclude is read after include. that way i can include node_modules
# all day long – exclude does still filter it out because excluding is
# happening after including
# this is logical though not intuitive
# include: ['node_modules']

keep_files:
- bucket
- node_modules

# Build settings
markdown: kramdown
permalink: pretty
