# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CODE4WD Conf
email: fogell@code4wd.com
description: > # this means to ignore newlines until "baseurl:"
  The largest OSS event on the Middle East
baseurl: "/code4wd-experiments" # the subpath of your site, e.g. /blog
url: "http://code4wd.com" # the base hostname & protocol for your site
twitter_username: fogelmania
github_username:  fogelmania

asset_path: "/bucket"

collections:
- talks
- speakers
- patterns

# this is mostly to override the default content of exclude
# although the updated version of minima brings excluding the
# Gemfiles as default.
# preferred would be to
# include:
#   - node_modules
# see https://talk.jekyllrb.com/t/include-node-modules-does-not-include-node-modules/3441/
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - Procfile
  - README.md

keep_files:
- bucket
- node_modules

# Build settings
markdown: kramdown
permalink: pretty
